name        : golang
version     : 1.5
release     : 5
homepage    : http://golang.org
source      :
    - https://storage.googleapis.com/golang/go1.5.src.tar.gz : be81abec996d5126c05f2d36facc8e58a94d9183a56f026fc9441401d80062db
license     : MIT
summary     : The Go programming language.
description : Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep     : no
strip       : no
clang : no
builddeps :
    - golang
rundeps     :
    - glibc
build       : |
    mkdir -p $srcdir/go-final
    %patch -p1 < $pkgfiles/eb950ecf.diff
    export GOROOT_FINAL="$srcdir"
    export GOROOT_BOOTSTRAP="%libdir%/go"
    export GOROOT="%libdir%/go"
    cd $srcdir/src
    GOOS=linux GOARCH=amd64 ./bootstrap.bash
    ./make.bash
    cd $srcdir
    # Cleanup
    rm -rf bootstrap go-final pkg/obj pkg/linux_amd64/internal/syscall/windows
    rm -rf test
install : |
    cd $srcdir
    install -d $installdir/usr/bin
    install -d $installdir/%libdir%/go
    cp -R $srcdir/* $installdir/%libdir%/go/
    ln -sv %libdir%/go/bin/go $installdir/usr/bin/.
    ln -sv %libdir%/go/bin/gofmt $installdir/usr/bin/.
    install -D -m 00644 $pkgfiles/go.profile $installdir/etc/profile.d/50-go.sh
