name        : golang
version     : 1.4.2
release     : 2
homepage    : http://golang.org
source      :
    - https://storage.googleapis.com/golang/go1.4.2.src.tar.gz : 299a6fd8f8adfdce15bc06bde926e7b252ae8e24dd5b16b7d8791ed79e7b5e9b
license     : MIT
summary     : The Go programming language.
description : Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep     : no
strip       : no
rundeps     :
    - glibc
build       : |
    ( export GOROOT_FINAL="%libdir%/go"; cd $srcdir/src; ./make.bash )
install : |
    cd $srcdir
    install -d $installdir/usr/bin
    install -d $installdir/%libdir%/go
    cp -R $srcdir/* $installdir/%libdir%/go/
    ln -sv %libdir%/go/bin/go $installdir/usr/bin/.
    ln -sv %libdir%/go/bin/gofmt $installdir/usr/bin/.
    install -D -m 00644 $pkgfiles/go.profile $installdir/etc/profile.d/50-go.sh
    
    goroot="%libdir%/go"
    
    find $installdir${goroot}/src -exec touch -r $installdir${goroot}/VERSION "{}" \;
    # and level out all the built archives
    touch -r $installdir${goroot}/VERSION  $installdir${goroot}/pkg
    find $installdir${goroot}/pkg -exec touch -r $installdir${goroot}/pkg "{}" \;
