name       : golang
version    : 1.21.0
release    : 101
homepage   : https://golang.org
source     :
    - https://golang.org/dl/go1.21.0.src.tar.gz : 818d46ede85682dd551ad378ef37a4d247006f12ec59b5b755601d2ce114369a
license    : BSD-3-Clause
summary    : The Go programming language
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - binutils-gold # Needed for src/cmd/go/note_test.go
    - llvm-clang    # Needed for src/cmd/link/cgo_test.go
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
environment: |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
setup      : |
    %apply_patches
build      : |
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    chmod +x $installdir/%libdir%/golang/bin/{go,gofmt}
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
    rm -rf $installdir/usr/lib64/golang/pkg/obj
