name       : golang
version    : '1.12'
release    : 34
homepage   : http://golang.org
source     :
    - https://dl.google.com/go/go1.12.src.tar.gz : 09c43d3336743866f2985f566db0520b36f4992aea2b4b2fd9f52f17049e88f2
license    : BSD-3-Clause
summary    : The Go programming language.
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
setup      : |
    # Patch build failures
    %patch -p1 < $pkgfiles/0001-os-test-Solus-uses-usr-bin-hostname-conform-and-don-.patch
    %patch -p1 < $pkgfiles/0001-Strip-out-some-broken-tests.patch
build      : |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
    rm -rf $installdir/usr/lib64/golang/pkg/obj/go-build/*
