name       : golang
version    : 1.7.4
release    : 11
homepage   : http://golang.org
source     :
    - https://storage.googleapis.com/golang/go1.7.4.src.tar.gz : 4c189111e9ba651a2bb3ee868aa881fab36b2f2da3409e80885ca758a6b614cc
license    : BSD-3-Clause
summary    : The Go programming language.
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
setup      : |
    # Temporary patch for https://github.com/golang/go/issues/18064 until Go 1.8
    %patch -p1 < $pkgfiles/0001-time-update-test-for-tzdata-2016g.patch
build      : |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
    # Patch build failures
    %patch -p1 < $pkgfiles/0001-os-test-Solus-uses-usr-bin-hostname-conform-and-don-.patch
    # Clang isn't supported as a primary compiler in Solus anymore.
    %patch -p1 < $pkgfiles/0002-Stop-forcing-Clang.-The-sanitizer-there-is-bricked.patch
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
