name       : golang
version    : 1.9.1
release    : 19
homepage   : http://golang.org
source     :
    - https://storage.googleapis.com/golang/go1.9.1.src.tar.gz : a84afc9dc7d64fe0fa84d4d735e2ece23831a22117b50dafc75c1484f1cb550e
license    : BSD-3-Clause
summary    : The Go programming language.
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
setup      : |
    # Patch build failures
    %patch -p1 < $pkgfiles/0001-os-test-Solus-uses-usr-bin-hostname-conform-and-don-.patch
    %patch -p1 < $pkgfiles/0001-cmd-cgo-force-O0.patch
    # Clang isn't supported as a primary compiler in Solus anymore.
    %patch -p1 < $pkgfiles/0002-Stop-forcing-Clang.-The-sanitizer-there-is-bricked.patch
build      : |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
