name       : golang
version    : 1.16.3
release    : 71
homepage   : https://golang.org
source     :
    - https://golang.org/dl/go1.16.3.src.tar.gz : b298d29de9236ca47a023e382313bcc2d2eed31dfa706b60a04103ce83a71a25
license    : BSD-3-Clause
summary    : The Go programming language.
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - binutils-gold # Needed for src/cmd/go/note_test.go
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
setup      : |
    # Patch build failures
    %patch -p1 < $pkgfiles/0001-os-test-Solus-uses-usr-bin-hostname-conform-and-don-.patch
    %patch -p1 < $pkgfiles/0001-Strip-out-some-broken-tests.patch
build      : |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    chmod +x $installdir/%libdir%/golang/bin/{go,gofmt}
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
    rm -rf $installdir/usr/lib64/golang/pkg/obj/go-build/*
