name       : golang
version    : 1.8.0
release    : 14
homepage   : http://golang.org
source     :
    - https://storage.googleapis.com/golang/go1.8.src.tar.gz : 406865f587b44be7092f206d73fc1de252600b79b3cacc587b74b5ef5c623596
license    : BSD-3-Clause
summary    : The Go programming language.
description: Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.
autodep    : no
strip      : no
component  : programming
builddeps  :
    - golang
rundeps    :
    - glibc
replaces   :
    - golang-binary
setup      : |
    # Patch build failures
    %patch -p1 < $pkgfiles/0001-os-test-Solus-uses-usr-bin-hostname-conform-and-don-.patch
    # Clang isn't supported as a primary compiler in Solus anymore.
    %patch -p1 < $pkgfiles/0002-Stop-forcing-Clang.-The-sanitizer-there-is-bricked.patch
build      : |
    export GOROOT_BOOTSTRAP="%libdir%/golang"
    export GOROOT_FINAL="%libdir%/golang"
    # Build and run test suites
    pushd src
    bash ./all.bash

    # Install into this working tree
    popd
    GOROOT=$(pwd) PATH=$(pwd)/bin:$PATH go install -buildmode=shared std
install    : |
    mkdir -p $installdir/%libdir%/golang
    mkdir -p $installdir/usr/bin
    cp -a *  $installdir/%libdir%/golang
    ln -s %libdir%/golang/bin/go $installdir/usr/bin/go
    ln -s %libdir%/golang/bin/gofmt $installdir/usr/bin/gofmt
